# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'BlocNotes' do
	pod 'UITextView+Placeholder'
	pod 'ObjectiveRecord'
end

target 'BlocNotesTests' do

end

